export const DO_LOGIN_SUCCESS = "DO_LOGIN_SUCCESS";
export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";

export const FETCH_MEMORIES_SUCCESS = "FETCH_MEMORIES_SUCCESS";
